name: Update README

on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    name: Update Profile README

    steps:
      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.4.1
